apiVersion: apps/v1
kind: Deployment
metadata:
  name: files-dp
  namespace: personal
  labels:
    app: files-dp
spec:
  replicas: 1
  revisionHistoryLimit: 0  # Retains only the last ReplicaSet
  selector:
    matchLabels:
      app: files-dp
  template:
    metadata:
      labels:
        app: files-dp
    spec:
      containers:
      - name: files-dp-container
        files: 192.168.1.2:32000/filesprg:latest
        filesPullPolicy: Always   # Ensure the latest files is always pulled
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: files-cm    # Reference to the ConfigMap for environment variables
        volumeMounts:
        - name: filess-volume
          mountPath: /app/dinara  # This is where the PVC for filess will be mounted
      volumes:
      - name: filess-volume
        persistentVolumeClaim:
          claimName: pvc-filess-hostpath  # Reference to the PVC for filess
