apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-files-hostpath
  namespace: personal
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""  # This must be empty to bind to the manual PV
